/*
 * Copyright (c) 2023 Renesas Electronics Corporation and/or its affiliates
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stdio.h>
#include "hal_data.h"
#include "cm33_fpu_start.h"

#define CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_ON     (0x01012E1E)
#define CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_OFF    (0x0001312C)
#define CM33FPU_PRV_CPG_CLKON_CM33_INITVAL                 (0x01000100)

#define CM33FPU_PRV_CPG_RST_CM33_NSYSRESET_DEASSERT        (0x04000400)
#define CM33FPU_PRV_CPG_RST_CM33_ALLRESET_DEASSERT         (0x07000700)
#define CM33FPU_PRV_CPG_RSTMON_CM33_CM33FPU_BITS           (0x00000700)

void release_reset_cm33_fpu (void)
{
    if ((R_SYSC->SYS_LSI_MODE & R_SYSC_SYS_LSI_MODE_STAT_MD_CLKS_Msk) != 0)
    {
        /* SSCG is enabled */
        R_SYSC->SYS_CM33FPU_CFG0 = CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_ON;
        R_SYSC->SYS_CM33FPU_CFG1 = CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_ON;
    }
    else
    {
        /* SSCG is disabled */
        R_SYSC->SYS_CM33FPU_CFG0 = CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_OFF;
        R_SYSC->SYS_CM33FPU_CFG1 = CM33FPU_PRV_SYS_CM33FPU_CFG_INITVAL_FOR_SSC_OFF;
    }

    /* Set Cortex-M33_FPU Secure/Non-Secure vector address. */
    R_SYSC->SYS_CM33FPU_CFG2 = CM33_FPU_RESET_VECTOR_ADDRESS;
    R_SYSC->SYS_CM33FPU_CFG3 = CM33_FPU_RESET_VECTOR_ADDRESS;

    R_CPG->CPG_CLKON_CM33 = CM33FPU_PRV_CPG_CLKON_CM33_INITVAL;

    FSP_HARDWARE_REGISTER_WAIT((R_CPG_CPG_CLKON_CM33_CLK8_ON_Msk & R_CPG->CPG_CLKMON_CM33),
                               R_CPG_CPG_CLKON_CM33_CLK8_ON_Msk);

    R_CPG->CPG_RST_CM33 = CM33FPU_PRV_CPG_RST_CM33_NSYSRESET_DEASSERT;

    R_CPG->CPG_RST_CM33 = CM33FPU_PRV_CPG_RST_CM33_ALLRESET_DEASSERT;

    FSP_HARDWARE_REGISTER_WAIT((CM33FPU_PRV_CPG_RSTMON_CM33_CM33FPU_BITS & R_CPG->CPG_RSTMON_CM33), 0);
}

void load_cm33fpu_prog (void)
{
    memcpy((void *) (CM33_FPU_RESET_VECTOR_ADDRESS), (void *) (RZG3S_SPIROM_CM33FPU_BASE), RZG3S_CM33FPU_FW_SIZE_MAX);
}
