/*
 * Copyright (c) 2023 Renesas Electronics Corporation and/or its affiliates
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stdio.h>
#include "hal_data.h"
#include "ca55_start.h"

#define CA55_PRV_CPG_CLKON_CA55_ENABLE_CLOCK              (0x003F003FU)
#define CA55_PRV_CPG_CLKMON_CA55_ENABLED_CLOCK            (0x0000003FU)

#define CA55_PRV_CPG_RST_CA55_ASSERT_RESET_CA55           (0x1FFF1C00U)
#define CA55_PRV_CPG_RST_CA55_RELEASE_RESET_CA55          (0x1FFF1FF7U)

#define CA55_PRV_CPG_RSTMON_CA55_ASSERTED_RESET_CA55      (0x000003FFU)
#define CA55_PRV_CPG_RSTMON_CA55_RELEASED_RESET_CA55      (0x00000008U)

#define CA55_PRV_CPG_CLUSTER_PCHCTL_SET_REQ               (0x00480001U)
#define CA55_PRV_CPG_CLUSTER_PCHCTL_CLR_REQ               (0x00480000U)

#define CA55_PRV_CPG_CLUSTER_PCHMON_ASSERTRED_PACCEPT     (0x00000001U)
#define CA55_PRV_CPG_CLUSTER_PCHMON_DEASSERTED_PACCEPT    (0x00000000U)

#define CA55_PRV_CPG_CORE0_PCHCTL_SET_REQ                 (0x00080001U)
#define CA55_PRV_CPG_CORE0_PCHCTL_CLR_REQ                 (0x00080000U)

#define CA55_PRV_CPG_CORE0_PCHMON_ASSERTED_PACCEPT0       (0x00000001U)
#define CA55_PRV_CPG_CORE0_PCHMON_DEASSERTED_PACCEPT0     (0x00000000U)

void release_reset_ca55 (void)
{
    /* Set Cortex-A55 Core0 Reset vector address. */
    R_SYSC->SYS_CA55_CFG_RVAH0 = 0;
    R_SYSC->SYS_CA55_CFG_RVAL0 = CA55_RESET_VECTOR_ADDRESS;

    R_CPG->CPG_CLKON_CA55 = CA55_PRV_CPG_CLKON_CA55_ENABLE_CLOCK;

    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_CLKMON_CA55, CA55_PRV_CPG_CLKMON_CA55_ENABLED_CLOCK);

    R_CPG->CPG_CLUSTER_PCHCTL = CA55_PRV_CPG_CLUSTER_PCHCTL_SET_REQ;

    R_CPG->CPG_CORE0_PCHCTL = CA55_PRV_CPG_CORE0_PCHCTL_SET_REQ;

    R_CPG->CPG_RST_CA55 = CA55_PRV_CPG_RST_CA55_ASSERT_RESET_CA55;

    /* Confirm that all signals of Cortex-A55 are in the reset state. */
    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_RSTMON_CA55, CA55_PRV_CPG_RSTMON_CA55_ASSERTED_RESET_CA55);

    R_CPG->CPG_RST_CA55 = CA55_PRV_CPG_RST_CA55_RELEASE_RESET_CA55;

    /* Confirm that all signals of Cortex-A55 are in the non-reset state. */
    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_RSTMON_CA55, CA55_PRV_CPG_RSTMON_CA55_RELEASED_RESET_CA55);

    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_CLUSTER_PCHMON, CA55_PRV_CPG_CLUSTER_PCHMON_ASSERTRED_PACCEPT);

    R_CPG->CPG_CLUSTER_PCHCTL = CA55_PRV_CPG_CLUSTER_PCHCTL_CLR_REQ;

    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_CLUSTER_PCHMON, CA55_PRV_CPG_CLUSTER_PCHMON_DEASSERTED_PACCEPT);

    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_CORE0_PCHMON, CA55_PRV_CPG_CORE0_PCHMON_ASSERTED_PACCEPT0);

    R_CPG->CPG_CORE0_PCHCTL = CA55_PRV_CPG_CORE0_PCHCTL_CLR_REQ;

    FSP_HARDWARE_REGISTER_WAIT(R_CPG->CPG_CORE0_PCHMON, CA55_PRV_CPG_CORE0_PCHMON_DEASSERTED_PACCEPT0);
}

void load_ca55_prog (void)
{
    memcpy((void *) (CA55_RESET_VECTOR_ADDRESS), (void *) (RZG3S_SPIROM_BL2_BASE), RZG3S_BL2_SIZE_MAX);
}
