/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/*
 * Copyright (c) 2023 Renesas Electronics Corporation and/or its affiliates
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "hal_data.h"
#include "xspi_init.h"
#include "ca55_start.h"
#include "cm33_fpu_start.h"
#include "common_utils.h"
#include "spi_ep.h"
#define MODULE_NAME             "r_rspi"

/*******************************************************************************************************************//**
 * @addtogroup r_rspi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version =
    { RESET_VALUE };
    unsigned char rByte[BUFFER_SIZE_DOWN] =
    { RESET_VALUE };
    uint8_t converted_rtt_input = RESET_VALUE;

    /* version get API for FLEX pack information */
    R_FSP_VersionGet (&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize SPI driver */
    err = spi_init ();

    if (FSP_SUCCESS != err)
    { /* SPI module init failed */
        APP_PRINT("\r\n ** RSPI INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** RSPI INIT SUCCESSFUL ** \r\n");
    }

    /* Menu for User Selection */
    APP_PRINT("\r\nSelect from the below Menu options\r\n");
    APP_PRINT("\r\nPress 1 for Write() to Pmod SF3");
    APP_PRINT("\r\nPress 2 for Read() from Pmod SF3");
    APP_PRINT("\r\nPress 3 to Exit\r\n");

    while (EXIT != converted_rtt_input)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            converted_rtt_input = (uint8_t) atoi ((char*) rByte);

            switch (converted_rtt_input)
            {
                case WRITE:
                    err = spi_write ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** RSPI WRITE to Pmod SF3 Demo failed **  \r\n");
                        spi_clean_up ();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** RSPI WRITE to Pmod SF3 Demo Successful **  \r\n");
                    }
                break;
                case READ:
                    err = spi_read ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** RSPI READ from Pmod SF3 Demo failed **  \r\n");
                        spi_clean_up ();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** RSPI READ from Pmod SF3 Demo Successful **  \r\n");
                    }
                break;
                case EXIT:
                    err = spi_exit_demo ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** RSPI EXIT Demo failed ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** RSPI EXIT Demo Successful ** \r\n");
                    }
                break;
                default:
                    /* Menu for User Selection */
                    APP_PRINT("\r\nSelect from the below Menu options\r\n");
                    APP_PRINT("\r\nPress 1 for Write() to Pmod SF3");
                    APP_PRINT("\r\nPress 2 for Read() from Pmod SF3");
                    APP_PRINT("\r\nPress 3 to Exit\r\n");
                break;
            }

            if ((WRITE <= converted_rtt_input) && (EXIT > converted_rtt_input))
            {
                APP_PRINT("\r\nEnter any other key to go back to the main menu\r\n");
            }
        }
    }

    APP_PRINT(RTT_CTRL_TEXT_BRIGHT_CYAN "\r\nExiting RSPI demo....\r\n" RTT_CTRL_RESET);
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        if (0 == (R_SYSC_SYS_LSI_MODE_STAT_BOOTCPUSEL_Msk & R_SYSC->SYS_LSI_MODE))
        {
            xspi_open();

#if BSP_CFG_MCU_LAUNCH_CM33_FPU

            /* Load Cortex-M33_FPU program to SRAM(MCPU) */
            load_cm33fpu_prog();

            /* Release reset of Cortex-M33_FPU */
            release_reset_cm33_fpu();
#endif

#if BSP_CFG_MCU_LAUNCH_CA55

            /* Load Cortex-A55 program to SRAM(ACPU) */
            load_ca55_prog();

            xspi_close();

            /* Release reset of Cortex-A55(Core0) */
            release_reset_ca55();
#endif
        }
    }
}
/*******************************************************************************************************************//**
 * @} (end addtogroup r_rspi_ep)
 **********************************************************************************************************************/
